### Create product
POST http://localhost:8000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgyNDAxMjEsInN1YiI6IjcwNjkyZGVmLWY5YjItNGM4Zi05ZTMzLTUxNTNjOWIzYzM3ZiJ9.vnuQK8-TsRryo2V1hfSZRIbw7YK7qDJXOYGx5oQCloA

{
  "name": "Product Test",
  "price": 4.20
}

### Get product by id
GET http://localhost:8000/products/de56e5a5-ba17-442d-bc30-9d57896b2154
Content-Type: application/json

### Update product by id
PUT http://localhost:8000/products/de56e5a5-ba17-442d-bc30-9d57896b2154
Content-Type: application/json

{
  "name": "Product Test Updated",
  "price": 20.5
}

### Delete product by id
DELETE http://localhost:8000/products/de56e5a5-ba17-442d-bc30-9d57896b2154
Content-Type: application/json

### Get all products
GET http://localhost:8000/products
Content-Type: application/json

### Get all products paginated and sorted
GET http://localhost:8000/products?limit=10&page=1sort=asc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgyNDAxMjEsInN1YiI6IjcwNjkyZGVmLWY5YjItNGM4Zi05ZTMzLTUxNTNjOWIzYzM3ZiJ9.vnuQK8-TsRryo2V1hfSZRIbw7YK7qDJXOYGx5oQCloA
