POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "RenanMav",
  "email": "me@renanmav.xyz",
  "password": "password"
}

###

POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
  "email": "me@renanmav.xyz",
  "password": "password"
}