basePath: /
host: localhost:8000
info:
  contact: {}
  description: Product API with authentication
  title: GoExpert API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
